import math

BOUNDS = (0.0, 10.0)

N_SEEDS = 30
OBSTACLE_FRACTION = 0.15
THREAT_FRACTION = 0.15
MIN_REACHABLE = 10

GAMMA = 0.95
PLANNING_HORIZON = 3

SEARCH_RADIUS_DIST = 2.0
P_FOUND_NEAR = 0.90
P_FALSE_ALARM = 0.02

MOVE_COST = -1.0
BLOCKED_PENALTY = -5.0
THREAT_OCCUPANCY_PENALTY = -3.0
THREAT_ENTRY_PENALTY = -5.0
SEARCH_FOUND_REWARD = 100.0
SEARCH_NOT_FOUND_PENALTY = -2.0

MAX_SEARCH_STEPS = 30
MAX_RETURN_STEPS = 40

CANONICAL_ANGLES = {
    "RIGHT": 0.0,
    "UP": math.pi / 2,
    "LEFT": math.pi,
    "DOWN": -math.pi / 2,
}
MOVE_ACTIONS = ("UP", "DOWN", "LEFT", "RIGHT")
ACTIONS_SEARCH = ("UP", "DOWN", "LEFT", "RIGHT", "SEARCH")
ACTIONS_RETURN = MOVE_ACTIONS

ROLE_COLORS = {
    "free": "#e8e8e8",
    "obstacle": "#2b2b2b",
    "threat": "#f4a259",
}